name: test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.6.0

      - name: Configure, build, and test this project
        uses: threeal/cmake-action@v1.3.0
        with:
          args: -DBUILD_TESTING=ON
          run-test: true

      - name: Check code coverage
        uses: threeal/gcovr-action@v0.2.0
        with:
          exclude: build/*
          fail-under-line: 80

  check-warning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.6.0

      - name: Configure and build this project
        uses: threeal/cmake-action@v1.3.0
        with:
          cxx-flags: -Werror
          args: -DBUILD_TESTING=ON
          run-build: true

  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.6.0

      - name: Install cmake-format
        run: pip3 install cmake-format

      - name: Configure CMake
        run: cmake . -B build

      - name: Check code formatting
        run: |
          cmake --build build --target format
          cmake --build build --target check-format
